<?php
/**
 * @package WordPress
 * @subpackage Default_Theme
 */

//DO NOT EDIT THIS FILE!!

// this is for Set featured image
add_theme_support( 'post-thumbnails' ); 

//Adds borwser class so we can style according to browser
function organizedthemes_browser_body_class($classes) {
 
    global $is_gecko, $is_IE, $is_opera, $is_safari, $is_chrome;
 
    if($is_gecko)      $classes[] = 'firefox';
    elseif($is_opera)  $classes[] = 'opera';
    elseif($is_safari) $classes[] = 'safari';
    elseif($is_chrome) $classes[] = 'chrome';
    elseif($is_IE)     $classes[] = 'ie';
    else               $classes[] = 'unknown';
 
    return $classes;
 
}
add_filter('body_class','organizedthemes_browser_body_class');


?>